config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'pages#about'
  get 'about', to: 'pages#about'
  get 'gallery', to: 'pages#gallery'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end
class PagesController < ApplicationController
  def gallery
  end
end
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE >
  <head>
    <title>Catbear</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</>

app/views/pages/about.html.erb
<body background=<%= image_path 'https://www.drodd.com/images16/black-color21.png' %>>

<%= image_tag "asset46.png", alt: "logo", width: 200 %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4));">
<div class="container">

<p class="menu">
<%= link_to "Gallery ➚", gallery_path %></p>
</div>
</div>
<div class="banner-about" style="black">
  <div class="container">

    <p style="font-size: 21">
    <strong>Nea Noc</strong>
    </p>
    <p style="font-size: 13;">they/she</p>
<p>Interdisciplinary creator and researcher based in Tiohtià:ke/ Montreal. </p>
<p>Interested in the intersections of art, technology, grief, language, and privacy. </p>
<p>🌐 🌐 🌐</p>
<p>:::::::::::: Links ::::::::::::</p>

    <a href="https://www.behance.net/neanoc">
    <p style="color: pink">behance</p></a>
    <a href="https://github.com/n3b0">
    <p style="color: blue">github</p></a>
    <a href="https://www.linkedin.com/in/nea-noc/">
    <p style="color: white">linkedin</p></a></p>
    <a href="https://www.linkedin.com/in/nea-noc/">
  </div>
</div>
<%# scrolling stop + footer %>
<%# email address to link %>
<%# move about page to root %>

app/views/pages/gallery.html.erb
<body background=<%= image_path 'https://www.drodd.com/images16/black-color21.png' %>>
<div class="logogallery">
<%= image_tag "revolve.png", alt: "logo", width: 80 %>
</div>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4));">
<div class="container">
<p class="menu"><%= link_to "Home ⤴", root_path %></p>

</div>
</div>

<div class="banner-tbd" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4));">
<div class="container">
<p><p>Coming soon 🗝</p></p>
</div>
</div>

app/views/pages/home.html.erb
<%# <h1>This is the about page for catbear</h1> %>
<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://jooinn.com/images/white-clouds-and-blue-sky-3.jpg);">
  <div class="container">
    <h1>catbear 🐱‍💻🧸 is my <strong>website</strong> that I am <strong>building</strong>!</h1>
    <p>I'm anxious but I'm doing it.</p>
    <a class="btn btn-flat" href="#">catbear</a>
  </div>
</div> %>
<body background=<%= image_path 'https://www.drodd.com/images16/white-color21.png' %>>
<h1>catbear/home</h1>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.explicit.bing.net%2Fth%3Fid%3DOIP.cq2F1ltSo2frtm9UZqhVawHaDt%26pid%3DApi&f=1&ipt=62d6d79db08fab4180ae63e136814d8b17f539612f320a32d012818af475a07b&ipo=images;)">
  <div class="container">
    <%# <h2>catbear</h2> %>
    <p>🄷🄴🄻🄻🄾 🅆🄾🅁🄻🄳
this is the home page</p>
    <%# <a class="btn btn-flat" href="#">love</a> %>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.explicit.bing.net%2Fth%3Fid%3DOIP.cq2F1ltSo2frtm9UZqhVawHaDt%26pid%3DApi&f=1&ipt=62d6d79db08fab4180ae63e136814d8b17f539612f320a32d012818af475a07b&ipo=images);">
  <div class="container">
    <%# <h2>catbear</h2> %>
    <p>🄷🄴🄻🄻🄾 🅆🄾🅁🄻🄳
🄸'🄼 🄱🅄🄸🄻🄳🄸🄽🄶 🅃🄷🄸🅂 🅆🄴🄱🅂🄸🅃🄴</p>
    <%# <a class="btn btn-flat" href="#">love</a> %>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.explicit.bing.net%2Fth%3Fid%3DOIP.cq2F1ltSo2frtm9UZqhVawHaDt%26pid%3DApi&f=1&ipt=62d6d79db08fab4180ae63e136814d8b17f539612f320a32d012818af475a07b&ipo=images);">
  <div class="container">
    <%# <h2>catbear</h2> %>
    <p>🄷🄴🄻🄻🄾 🅆🄾🅁🄻🄳
🄸'🄼 🄱🅄🄸🄻🄳🄸🄽🄶 🅃🄷🄸🅂 🅆🄴🄱🅂🄸🅃🄴</p>
    <%# <a class="btn btn-flat" href="#">love</a> %>
  </div>
</div>

</div>


<div class="main">
  <p>Some text some text some text some text..</p>
</div>

app/views/pages/index.html.erb
<body background=<%= image_path 'https://www.drodd.com/images16/white-color21.png' %>>
<div class="logo">
<%= image_tag "digilogo.png", alt: "logo", width: 80 %>
</div>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
<div class="container">
<p>🄷🄴🄻🄻🄾 🅆🄾🅁🄻🄳 </p>
<p class="menu"><%= link_to "About Nea", about_path %></p>
<p><%= link_to "Gallery", gallery_path %></p>
</div>
</div>